name: Build

on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
     
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
 
    - name: DirectX
      run: |
        choco install directx
        tree "C:/Program Files (x86)/Microsoft DirectX SDK"
        exit 1
 
    - name: Build
      run: msbuild 0CC-FamiTracker.vcxproj /m /verbosity:minimal /p:Configuration=Release

    - name: Upload
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build
        path: Release\0CC-FamiTracker.exe
